Document: skiboot
Title: Debian skiboot Manual
Author: <insert document author here>
Abstract: This manual describes what skiboot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/skiboot/skiboot.sgml.gz

Format: postscript
Files: /usr/share/doc/skiboot/skiboot.ps.gz

Format: text
Files: /usr/share/doc/skiboot/skiboot.text.gz

Format: HTML
Index: /usr/share/doc/skiboot/html/index.html
Files: /usr/share/doc/skiboot/html/*.html
